src/Model/Ticket/Entity/Ticket/State.php
<?php

declare(strict_types=1);

namespace App\Model\Ticket\Entity\Ticket;

use Doctrine\ORM\Mapping as ORM;
use Webmozart\Assert\Assert;

/**
 * @ORM\Embeddable
 */
class State
{
    public const SUPPORT_READ = 'support_read';
    public const SUPPORT_REPLY = 'support_reply';
    public const SUPPORT_CLOSED = 'support_closed';
    public const AUTHOR_READ = 'author_read';
    public const AUTHOR_ASKED = 'author_asked';
    public const AUTHOR_CLOSED = 'author_closed';

    /**
     * @ORM\Column(type="string", length=32, nullable=false)
     */
    private $state;

    public function __construct(string $state = 'author_asked')
    {
        Assert::oneOf($state, [
            self::SUPPORT_READ,
            self::SUPPORT_REPLY,
            self::SUPPORT_CLOSED,
            self::AUTHOR_CLOSED,
            self::AUTHOR_READ,
            self::AUTHOR_ASKED
        ]);

        $this->state = $state;
    }

    public function isNewForAuthor(): bool
    {
        return $this->state === self::SUPPORT_REPLY;
    }

    public function isNewForSupport(): bool
    {
        return $this->state === self::AUTHOR_ASKED;
    }

    public function authorRead(): self
    {
        $this->state = self::AUTHOR_READ;
        return $this;
    }

    public function authorAsked(): self
    {
        $this->state = self::AUTHOR_ASKED;
        return $this;
    }

    public function authorClosed(): self
    {
        $this->state = self::AUTHOR_CLOSED;
        return $this;
    }

    public function supportRead(): self
    {
        $this->state = self::SUPPORT_READ;
        return $this;
    }

    public function supportReply(): self
    {
        $this->state = self::SUPPORT_REPLY;
        return $this;
    }

    public function supportClosed(): self
    {
        $this->state = self::SUPPORT_CLOSED;
        return $this;
    }

}

src/Controller/Cpanel/ArticleController.php
<?php

declare(strict_types=1);

namespace App\Controller\Cpanel;

use App\Controller\ErrorHandler;
use App\Model\Article\Entity\Article;
use App\Model\Article\Repository\ArticleRepository;
use App\Model\Article\UseCase\Create;
use App\Model\Article\UseCase\Edit;
use App\Model\Article\UseCase\Image;
use App\Model\Article\UseCase\Move;
use App\Model\Article\UseCase\Remove;
use Knp\Component\Pager\PaginatorInterface;
use Liip\ImagineBundle\Service\FilterService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ArticleController extends AbstractController
{
    private const PER_PAGE = 15;
    private $errors;

    public function __construct(ErrorHandler $errors)
    {
        $this->errors = $errors;
    }

    /**
     * @Route("/articles", name="articles")
     */
    public function list(Request $request, ArticleRepository $articles, PaginatorInterface $paginator)
    {
        $pagination = $paginator->paginate(
            $articles->getAll(),
            $request->query->getInt('page', 1),
            self::PER_PAGE
        );
        return $this->render('cpanel/article/list.html.twig', [
            'articles' => $pagination
        ]);
    }

    /**
     * @Route("/article/create", name="article.create")
     */
    public function create(Request $request, Create\Handler $handler)
    {
        $command = new Create\Command();
        $form = $this->createForm(Create\Form::class, $command);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            try {
                $handler->handle($command);
                $this->addFlash('success', 'article.created');
                return $this->redirectToRoute('cpanel.articles');
            } catch (\DomainException $e) {
                $this->errors->handle($e);
                $this->addFlash('error', $e->getMessage());
            }
        }

        return $this->render('cpanel/article/create.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/article/{id}", name="article", methods={"POST","GET"})
     */
    public function edit(Article $article, Request $request, Edit\Handler $handler)
    {
        $command = new Edit\Command($article);

        $form = $this->createForm(Edit\Form::class, $command);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            try {
                $handler->handle($command);
                $this->addFlash('success', 'article.updated');
            } catch (\DomainException $e) {
                $this->errors->handle($e);
                $this->addFlash('error', $e->getMessage());
            }
        }

        return $this->render('cpanel/article/edit.html.twig', [
            'form' => $form->createView(),
            'article'=> $article,
        ]);
    }

    /**
     * @Route("/article/{id}/remove", name="article.remove")
     */
    public function delete(Article $article, Request $request, Remove\Handler $handler)
    {
        if (!$this->isCsrfTokenValid('any', $request->request->get('token_csrf'))) {
            return $this->json(null, 401);
        }
        $command = new Remove\Command($article->getId());
        $handler->handle($command);
        return $this->json(null, 204);
    }

    /**
     * @Route("/article/images/upload", name="article.image.upload", methods={"POST","PUT"})
     */
    public function upload(Request $request, Image\Upload\Handler $handler, FilterService $filterImages): Response
    {
        if (!$this->isCsrfTokenValid('any', $request->request->get('token_csrf'))) {
            return $this->json(null, 401);
        }
        $command = new  Image\Upload\Command($request->files->get('file'));
        try {
            $file = $handler->handle($command);
        } catch (\DomainException $e) {
            $this->errors->handle($e);
            return $this->json($e->getMessage(), 400);
        }

        return $this->json([
            'id' => $file->getId(),
            'src' => $filterImages->getUrlOfFilteredImage($file->getPath(), 'article_215_320')],
            201, []);
    }
}

src/Controller/Cpanel/AuthController.php
<?php

declare(strict_types=1);

namespace App\Controller\Cpanel;

use App\Model\Cpanel\UseCase\Login;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;

class AuthController extends AbstractController
{

    /**
     * @Route("/login",name="login")
     * @param AuthenticationUtils $authenticationUtils
     * @return Response
     */
    public function auth(AuthenticationUtils $authenticationUtils): Response
    {
        $form = $this->createForm(Login\Form::class);

        $error = $authenticationUtils->getLastAuthenticationError();
        $lastUsername = $authenticationUtils->getLastUsername();

        return $this->render('cpanel/auth/login.html.twig', [
            'last_username' => $lastUsername,
            'error' => $error,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/logout",name="logout")
     * @return Response
     * @throws \Exception
     */
    public function logout(): Response
    {
        throw new \Exception('will be intercepted before');
    }


}

src/Controller/Cpanel/BasketController.php
<?php

declare(strict_types=1);

namespace App\Controller\Cpanel;

use App\Controller\ErrorHandler;
use App\Model\Ecommerce\ReadModel\Product\ProductFetcher;
use App\Model\Order\Entity\Order;
use App\Model\Order\UseCase\Basket;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class BasketController extends AbstractController
{
    private $errors;

    public function __construct(ErrorHandler $errors)
    {
        $this->errors = $errors;
    }

    /**
     * @Route("/order/{id}/basket", methods={"DELETE"})
     */
    public function removeProduct(Order $order, Request $request, Basket\Remove\Handler $handler)
    {
        $product = $request->request->getInt('id');
        try {
            $handler->handle(Basket\Remove\Command::fromOrder($order, $product));
        } catch (\DomainException $e) {
            return $this->json(['error' => $e->getMessage()], 406);
        }
        return $this->json([], 204);
    }

    /**
     * @Route("/order/{id}/basket", methods={"POST"})
     */
    public function addProduct(Order $order, Request $request, Basket\Add\Handler $handler)
    {
        $product = $request->request->getInt('id');
        try {
            $handler->handle(Basket\Add\Command::fromOrder($order, $product));
        } catch (\DomainException $e) {
            return $this->json(['error' => $e->getMessage()], 406);
        }
        return $this->json([], 200);
    }

    /**
     * @Route("/order/{id}/basket", name="order.basket", methods={"PUT"})
     */
    public function updateCountProduct(Order $order, Request $request, Basket\Update\Handler $handler)
    {
        $product = $request->request->getInt('id');
        $count = $request->request->getInt('count');
        try {
            $handler->handle(Basket\Update\Command::fromOrder($order, $product, $count));
        } catch (\DomainException $e) {
            return $this->json(['error' => $e->getMessage()], 406);
        }
        return $this->json([], 200);
    }

    /**
     * @Route("/order/{id}/basket", name="order.product.search", methods={"GET"})
     */
    public function searchProduct(Request $request, ProductFetcher $products)
    {
        $querySearch = $request->query->get('query', '');
        return $this->json($products->searchForBasket($querySearch));
    }
}

src/Controller/Cpanel/BuyersController.php
<?php

declare(strict_types=1);

namespace App\Controller\Cpanel;

use App\Controller\ErrorHandler;
use App\Model\Buyer\Entity\Buyer;
use App\Model\Cpanel\UseCase\Filter\Buyers;
use App\Model\Buyer\UseCase\Remove;
use App\Model\Buyer\UseCase\Setting\Information;
use App\Model\Buyer\Repository\BuyerRepository;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @IsGranted("ROLE_ROOT")
 */
class BuyersController extends AbstractController
{

    private const PER_PAGE = 20;
    private $errors;

    public function __construct(ErrorHandler $errors)
    {
        $this->errors = $errors;
    }

    /**
     * @Route("/buyers", name="buyers")
     */
    public function buyers(Request $request, BuyerRepository $buyers, Buyers\Filter $filter)
    {
        $form = $this->createForm(Buyers\Form::class, $filter);
        $form->handleRequest($request);

        $pagination = $buyers->search(
            $filter,
            $request->query->getInt('page', 1),
            self::PER_PAGE
        );

        return $this->render('cpanel/buyers/list.html.twig', [
            'pagination' => $pagination,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/buyer/{id}", name="buyer.edit", methods={"POST","GET"})
     */
    public function edit(Buyer $buyer, Request $request, Information\Handler $handler)
    {
        $command = Information\Command::fromBuyer($buyer);

        $form = $this->createForm(Information\Form::class, $command);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            try {
                $handler->handle($command);
                $this->addFlash('success', 'buyer.updated');
            } catch (\DomainException $e) {
                $this->errors->handle($e);
                $this->addFlash('error', $e->getMessage());
            }
        }

        return $this->render('cpanel/buyers/edit.html.twig', [
            'form' => $form->createView(),
            'buyer' => $buyer
        ]);
    }

    /**
     * @Route("/buyer/{id}", name="buyer.remove", methods={"DELETE"})
     */
    public function remove(Buyer $buyer, Request $request, Remove\Handler $handler)
    {
        if (!$this->isCsrfTokenValid('any', $request->request->get('token_csrf'))) {
            return $this->json(null, 401);
        }
        $command = new Remove\Command($buyer->getId());
        $handler->handle($command);
        return $this->json(null, 204);
    }
}

src/Controller/Cpanel/CategoryDealerController.php
<?php

declare(strict_types=1);

namespace App\Controller\Cpanel;

use App\Controller\ErrorHandler;
use App\Model\Cpanel\Entity\CategoryDealer;
use App\Model\Cpanel\Repository\CategoryDealerRepository;
use App\Model\Cpanel\UseCase\CategoryDealer\Edit;
use App\Model\Cpanel\UseCase\CategoryDealer\Create;
use App\Model\Cpanel\UseCase\CategoryDealer\MovePosition;
use Knp\Component\Pager\PaginatorInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Csrf\CsrfTokenManagerInterface;
use Doctrine\ORM\EntityManagerInterface;

/**
 * @IsGranted("ROLE_ROOT")
 */
class CategoryDealerController extends AbstractController
{

    private const PER_PAGE = 10;

    /**
     * @var ErrorHandler
     */
    private $errors;

    public function __construct(ErrorHandler $errors)
    {
        $this->errors = $errors;
    }

    /**
     * @Route("/categories-dealer", name="categories.dealer")
     */
    public function categories(Request $request, CategoryDealerRepository $categories, PaginatorInterface $paginator, CsrfTokenManagerInterface $csrfToken)
    {
        $pagination = $paginator->paginate(
            $categories->findBy([], ['position' => 'DESC']),
            $request->query->getInt('page', 1),
            self::PER_PAGE
        );

        return $this->render('cpanel/category_dealer/list.html.twig', [
            'pagination' => $pagination,
            'token_csrf' => $csrfToken->getToken('delete'),
        ]);
    }

    /**
     * @Route("/categories-dealer/add", name="categories.dealer.add")
     */
    public function add(Request $request, Create\Handler $handler)
    {
        $command = new Create\Command();

        $form = $this->createForm(Create\Form::class, $command);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            try {
                $handler->handle($command);
                $this->addFlash('success', 'category.dealer.created');
                return $this->redirectToRoute('cpanel.categories.dealer');
            } catch (\DomainException $e) {
                $this->errors->handle($e);
                $this->addFlash('error', $e->getMessage());
            }
        }
        return $this->render('cpanel/category_dealer/create.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/categories-dealer/{id}", name="category.dealer", methods={"POST","GET"})
     */
    public function edit(CategoryDealer $categoryDealer, Request $request, Edit\Handler $handler)
    {
        $command = Edit\Command::fromCategoryDealer($categoryDealer);

        $form = $this->createForm(Edit\Form::class, $command);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            try {
                $handler->handle($command);
                $this->addFlash('success', 'category.dealer.updated');
                return $this->redirectToRoute('cpanel.categories.dealer');
            } catch (\DomainException $e) {
                $this->errors->handle($e);
                $this->addFlash('error', $e->getMessage());
            }
        }

        return $this->render('cpanel/category_dealer/edit.html.twig', [
            'form' => $form->createView(),
            'category' => $categoryDealer,
        ]);
    }

    /**
     * @Route("/categories-dealer/{id}", name="category.dealer.delete", methods={"DELETE"})
     */
    public function delete(CategoryDealer $categoryDealer, Request $request, EntityManagerInterface $em)
    {
        if (!$this->isCsrfTokenValid('delete', $request->request->get('token_csrf'))) {
            return $this->json(null, 401);
        }
        $em->remove($categoryDealer);
        $em->flush();
        return $this->json(null, 204);
    }

    /**
     * @Route("/categories-dealer/{id}/position", name="category.dealer.position", methods={"POST","GET"})
     */
    public function position(CategoryDealer $categoryDealer, Request $request, MovePosition\Handler $handler)
    {
        if (!$this->isCsrfTokenValid('delete', $request->request->get('token_csrf'))) {
            return $this->json(null, 401);
        }
        $command = new MovePosition\Command($categoryDealer, $request->request->get('direction'));
        try {
            $handler->handle($command);
        } catch (\DomainException $e) {
            return $this->json(null, 204);
        }
        return $this->json(null, 200);
    }

}

templates/cpanel/ticket/_form_message.html.twig
{{ form_start(form,{
    attr: {
        class:'forms-sample',
        novalidate:'',
    }
}) }}

<div class="form-group">
    {{ form_widget(form.content, {attr: {
        class: 'form-control tinymce',
        rows:10
    }}) }}
    {{ form_errors(form.content) }}
</div>

<div class="form-group">
    {{ form_widget(form.file, {attr: {
        class: 'file-upload-default'
    }}) }}
    <div class="input-group col-xs-12">
        <input type="text" class="form-control file-upload-info file-upload-browse" readonly placeholder="Администратор может загружать любой файл">
        <span class="input-group-append">
            <button class="file-upload-browse btn btn-success" type="button">Прикрепить файл</button>
            <button class="file-upload-browse-clear btn btn-light ml-3" type="button">Сбросить файл</button>
        </span>
    </div>
    {{ form_errors(form.file) }}
</div>


<button type="submit" class="btn btn-primary mr-2 ">{{ name_sumbit }}</button>
{{ form_end(form) }}

templates/cpanel/ticket/list.html.twig
{% extends 'cpanel/content.html.twig' %}

{% block content %}
    <div class="content-wrapper">
        {% block breadcrumbs %}
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ path('cpanel.index') }}">Главная</a></li>
                <li class="breadcrumb-item active">Служба поддержки</li>
            </ol>
        {% endblock %}
        {% include 'cpanel/_flashes.html.twig' %}
        <div class="card">
            <div class="card-body dashboard-tabs p-0">
                <ul class="nav nav-tabs px-4" role="tablist">
                    <li class="nav-item">
                        <a class="nav-link {% if app.request.get('_route') == 'cpanel.tickets' %}active{% endif %}"  href="{{ path("cpanel.tickets")}}"
                          >Открытые вопросы</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if app.request.get('_route') == 'cpanel.tickets.closed' %}active{% endif %}"  href="{{ path("cpanel.tickets.closed")}}"
                          >Закрытые вопросы</a>
                    </li>
                </ul>
                <div class="tab-content py-0 px-0">
                    <div class="tab-pane fade active show pl-3 pr-3">

                        <div class="table-responsive">
                            {% if tickets|length>0 %}
                                <table class="table" >
                                    {% for ticket in tickets %}
                                        <tr>
                                            <td >
                                                {{ ticket.createdAt|date('d.m.Y H:i') }}
                                            </td>
                                            <td >
                                                {{ ticket.author.getShowName }}
                                            </td>
                                            <td  class="w-50">
                                                {% if ticket.state.newForSupport %}
                                                    <label class="badge badge-danger">Новые сообщения!</label>
                                                {% endif %}
                                                <b><a href="{{ path('cpanel.ticket',{id:ticket.id}) }}{% if ticket.state.newForAuthor %}#new{% endif %}">{{ ticket.header }}</a></b>
                                            </td>
                                            <td class="text-center">
                                                {% if ticket.status.isOpen %}
                                                    <label class="badge badge-success">В процессе</label>
                                                {% else %}
                                                    <label class="badge badge-secondary">Закрыто</label>
                                                {% endif %}
                                            </td>
                                        </tr>
                                    {% endfor %}
                                </table>
                            {% else %}
                                <div class="mt-4">В настоящий момент нет заявок в службу поддержки.</div>
                            {% endif %}
                        </div>

                        <input type="hidden" name="token_csrf" value="{{ csrf_token('any') }}"/>

                        <div class="navigation d-flex mt-4 col-lg-12">
                            <div class="ml-auto mr-auto">
                                {{ knp_pagination_render(tickets) }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>


    </div>
{% endblock %}

templates/cpanel/ticket/view.html.twig
{% extends 'cpanel/content.html.twig' %}

{% block title %}{{ parent() }} - Служба поддержки{% endblock %}
{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('ticket.tinymce') }}
{% endblock %}
{% block content %}
    <div class="content-wrapper">
        {% block breadcrumbs %}
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ path('cpanel.index') }}">Главная</a></li>
                <li class="breadcrumb-item"><a href="{{ path('cpanel.tickets') }}">Служба поддержки</a></li>
                <li class="breadcrumb-item active">Вопрос
                    #{{ ticket.id }}  {% if ticket.status.isClosed %}(Закрыт){% endif %}</li>
            </ol>
        {% endblock %}

        {% if ticket.status.isClosed %}
            <div class="alert alert-danger mb-4 mt-4 text-center">
                <b>Вопрос закрыт.</b>
            </div>
        {% endif %}

        {% include 'cpanel/_flashes.html.twig' %}

        <div class="row">

            <div class="col-lg-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <h2 class="card-title">{{ ticket.header }}</h2>
                        <div class="d-flex d-inline">
                            <div class="flex-grow-1"><p class="card-description">
                                    Дата создания заявки: {{ ticket.createdAt|date('d.m.Y H:i') }}
                                    {% if ticket.createdAt != ticket.updatedAt %}
                                        <br>
                                        Последние обновление:  {{ ticket.updatedAt|date('d.m.Y H:i') }}
                                    {% endif %}</p>
                            </div>
                            {% if ticket.status.isOpen %}
                                <form action="{{ path('cpanel.ticket.closed', { id: ticket.id }) }}" method="post"
                                      onsubmit="return confirm('Вы уверены, что хотите закрыть вопрос?')">
                                    <input type="hidden" name="token" value="{{ csrf_token('any') }}"/>
                                    <button type="submit" class="btn btn-success">Закрыть вопрос</button>
                                </form>
                            {% endif %}
                            <form action="{{ path('cpanel.ticket.delete', { id: ticket.id }) }}" method="post"
                                  onsubmit="return confirm('Вы уверены, что хотите удалить вопрос? Действие будет не отменить')">
                                <input type="hidden" name="token" value="{{ csrf_token('any') }}"/>
                                <button type="submit" class="btn btn-danger ml-3">Удалить</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            {% for message in ticket.messages %}
                <div class="col-lg-12 grid-margin stretch-card" {% if loop.last %}id="new"{% endif %}>
                    <div class="card">
                        <div class="card-body">
                            <div class="d-flex d-inline">
                                <p class="card-description mr-3">{{ message.createdAt|date('d.m.Y H:i') }}</p>
                                <b class="card-title">
                                    {% if message.author %}
                                        <a href="{{ path("cpanel.dealer.edit",{id:message.author.id}) }}">{{ message.author.getShowName }}</a>
                                    {% else %}
                                        <a href="{{ path("cpanel.profile",{id:message.support.id}) }}">
                                        {{ message.support.getShowName }}
                                        </a>
                                    {% endif %}</b>
                            </div>
                            <p>
                                {{ message.content|raw }}
                            </p>

                            {% if message.files|length>0 %}
                                <p class="mt-4"><b>Прикрепленный файл:</b></p>
                                {% for link in message.files %}
                                    <p class="ml-4"><a
                                                href="{{ path("cpanel.file",{id:link.file.id}) }}">{{ link.file.originalFilename }}</a>
                                    </p>
                                {% endfor %}
                            {% endif %}
                        </div>
                    </div>
                </div>
            {% endfor %}
            {% if ticket.status.isOpen %}
                <div class="col-lg-12 grid-margin stretch-card">
                    <div class="card">
                        <div class="card-body">
                            {{ include('cpanel/ticket/_form_message.html.twig',{
                                name_sumbit:'Ответить'
                            }) }}
                        </div>
                    </div>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}